import type { LegalPage } from '@/lib/types';

export const legalPages: LegalPage[] = [
  {
    _id: 'legal-privacy-policy',
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    body: "Last updated: 12 August 2026\n\n1. Who we are\n\nDepth X Ltd. (\"Depth X\", \"we\", \"us\", \"our\") is a company registered in England & Wales, company number 16162223, with its registered office at 71-75 Shelton Street, London, Covent Garden, London, England, WC2H 9JQ. This policy explains how we collect, use, and protect personal data when you use depthx.co.uk (the \"Site\").\n\n2. What data we collect\n\nWe collect the minimum data needed to run this Site:\n\n- Contact form submissions: your name, email address, the role you select (investor, researcher, or company), and the content of your message.\n- Aggregate usage data: the page you visited and the country your visit came from, used only in aggregate to understand which parts of the Site are useful. We do not use cookies for this, and we do not track individual visitors across sessions or build profiles of you.\n\n3. How we use your data\n\nWe use contact form submissions solely to respond to your enquiry and route it to the right team (investment, research collaboration, or commercial licensing). We use aggregate usage data solely to understand overall Site traffic and improve our content. We do not sell personal data, and we do not use it for advertising.\n\n4. Legal basis\n\nWe process contact form data on the basis of your consent (you choose to submit the form) and our legitimate interest in responding to business enquiries. We process aggregate usage data on the basis of our legitimate interest in understanding how the Site is used, in a way that does not identify you individually.\n\n5. Data retention\n\nWe retain contact form submissions for as long as needed to handle your enquiry and for a reasonable period afterwards for our records, after which they are deleted. Aggregate usage data is retained in aggregate form and is not linked to an identifiable individual.\n\n6. Who we share data with\n\nWe use Supabase, Inc. as our data hosting and infrastructure provider, which stores data on our behalf under its own data processing terms. We do not share your personal data with any other third party except where required by law.\n\n7. Your rights\n\nUnder UK GDPR, you have the right to request access to, correction of, or deletion of your personal data, to object to or restrict our processing of it, and to request a copy of it in a portable format. To exercise any of these rights, contact us at privacy@depthx.co.uk.\n\n8. Cookies\n\nThis Site does not use tracking or advertising cookies. Any cookies used are strictly necessary for the Site's admin panel to function (e.g. keeping you signed in).\n\n9. Changes to this policy\n\nWe may update this policy from time to time. The date at the top of this page shows when it was last revised.\n\n10. Contact\n\nQuestions about this policy can be sent to privacy@depthx.co.uk or by post to our registered office above.",
    updatedAt: '2026-08-12',
  },
  {
    _id: 'legal-terms-of-service',
    slug: 'terms-of-service',
    title: 'Terms of Service',
    body: "Last updated: 12 August 2026\n\n1. Acceptance of these terms\n\nBy accessing or using depthx.co.uk (the \"Site\"), you agree to these Terms of Use. If you do not agree, please do not use the Site. The Site is operated by Depth X Ltd., a company registered in England & Wales, company number 16162223, registered office at 71-75 Shelton Street, London, Covent Garden, London, England, WC2H 9JQ.\n\n2. Purpose of the Site\n\nThe Site is provided to share information about Depth X's research, patent portfolio, and licensing opportunities, and to allow investors, researchers, and commercial partners to get in touch. Nothing on the Site constitutes an offer to license any technology, an investment solicitation, or legal or financial advice; any such arrangement would be subject to a separate, signed agreement.\n\n3. Intellectual property\n\nAll content on the Site — including research descriptions, patent summaries, text, and design — is the property of Depth X Ltd. or its licensors and is protected by copyright and other intellectual property laws, unless otherwise stated. Patents referenced on the Site are the property of Depth X Ltd. and are protected independently of this Site's content. You may view and share Site content for personal, non-commercial reference, but may not reproduce, redistribute, or create derivative works from it without our written permission.\n\n4. Interactive demonstrations\n\nSome project pages may include interactive HTML demonstrations (\"product simulators\") intended to illustrate a technology's behaviour. These are provided for illustrative purposes only and do not represent a finished commercial product, warranty of functionality, or specification.\n\n5. No warranty\n\nThe Site and its content are provided \"as is\" without warranties of any kind, express or implied, including as to accuracy, completeness, or fitness for a particular purpose. Patent and licensing status shown on the Site is indicative and should be independently verified before you rely on it for a commercial decision.\n\n6. Limitation of liability\n\nTo the fullest extent permitted by law, Depth X Ltd. will not be liable for any indirect, incidental, or consequential loss arising from your use of the Site.\n\n7. Governing law\n\nThese terms are governed by the laws of England and Wales, and any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.\n\n8. Changes to these terms\n\nWe may update these terms from time to time. The date at the top of this page shows when it was last revised. Continued use of the Site after a change constitutes acceptance of the revised terms.\n\n9. Contact\n\nQuestions about these terms can be sent to legal@depthx.co.uk or by post to our registered office above.",
    updatedAt: '2026-08-12',
  },
];
